In [11]:
import yfinance as yf
import pandas as pd
import os
ticker_input = "AUR, AVTR, AZTA, CELH, DHX, DIOD, EVTL, GSAT, INTC, MXL, SATS, SEDG, SERV, SOFI, SVCO, TSLA, VEON, WRD"

tickers = [t.strip().upper() for t in ticker_input.split(',')]

data = []
for ticker in tickers:
    stock = yf.Ticker(ticker)
    info = stock.info
    data.append({
        'Ticker': ticker,
        'Trailing P/E': info.get('trailingPE', 'N/A'),
        'Forward P/E': info.get('forwardPE', 'N/A'),
        'Beta': info.get('beta', 'N/A'),
        '好看吗': '',
        '等什么': ''
    })

df = pd.DataFrame(data)

df.to_csv(os.path.expanduser('~/Desktop/Portfolio_Quality.csv'))


df

   Ticker Trailing P/E  Forward P/E   Beta 好看吗 等什么
0     AUR          N/A   -11.488890  2.598
1    AVTR    13.009616    11.973452  1.047
2    AZTA          N/A    72.833336  1.611
3    CELH     139.0606    46.826530  1.412
4     DHX          N/A    29.700000  1.443
5    DIOD     96.03636    20.083649  1.424
6    EVTL          N/A    -1.046656  1.193
7    GSAT          N/A -2354.000200  0.856
8    INTC          N/A    23.391752  1.113
9     MXL          N/A    39.277780  1.669
10   SATS          N/A   -10.476363  0.755
11   SEDG          N/A    -8.081633  1.588
12   SERV          N/A   -18.451612    N/A
13   SOFI    39.953487    59.241383  1.827
14   SVCO          N/A    15.531250    N/A
15   TSLA    184.93143    99.885800  2.461
16   VEON     7.737392     6.283899  1.496
17    WRD          N/A    -4.332624    N/A